# JAVA enviroment

FROM debian

MAINTAINER Du Than <dthan@student.hive.fi>

RUN apt-get update && apt-get upgrade -y && apt-get install -y default-jdk default-jre git vim

# docker build -t bonus00 .
# docker run --rm -ti bonus00