#!/bin/bash
RED='\033[0;31m'
YELLOW='\033[1;33m'
echo "${RED}Q: Get the list of the network interfaces of the machine
without displaying any detail for these interfaces. Only the list of names.\n"
echo "${YELLOW}A: ifconfig -l"
ifconfig -l
