#!/bin/bash
RED='\033[0;31m'
YELLOW='\033[1;33m'
echo "${RED}Q: Identify the MAC address of the Wi-Fi card\n"
echo "${YELLOW}A: ifconfig en1 | grep "ether" | cut -d \" \" -f 2"
ifconfig en1 | grep "ether" | cut -d " " -f 2
