#!/bin/bash
RED='\033[0;31m'
YELLOW='\033[1;33m'
echo "${RED}Q: Identifiy the default gateway in the routing table\n"
echo "${YELLOW}A: netstat -nr | grep -A 2 Internet: | grep default | awk '{print \$2}'"
netstat -nr | grep -A 2 Internet: | grep default | awk '{print $2}'
