#!/bin/bash
RED='\033[0;31m'
YELLOW='\033[1;33m'
echo "${RED}Q: Find the provider of slash16.org\n"
echo "${YELLOW}A: Amazon Technologies Inc.
NOTE: Using commands:
      host slash16.org
      whois 13.33.242.31\n"
