#!/bin/bash
RED='\033[0;31m'
YELLOW='\033[1;33m'
echo "${RED}Q: Identify the network devices between your computer and the slash16.org domain\n"
echo "${YELLOW}A: traceroute slash16.org"
traceroute slash16.org
