FROM debian:latest

MAINTAINER Du Than <dthan@student.hive.fi>

RUN apt-get update && apt-get upgrade -y && apt-get install -y build-essential git valgrind sudo

# docker build -t bonus03 .
# docker run --rm -ti bonus03