#!/bin/bash
echo "Write a script which displays only the login, UID and Path of each entry of the /etc/passwd file.\n"
echo "We use the command line: \n"
echo "cat /etc/passwd | awk -F ':' '{print \$1\"|\"\$3\"|\"\$7}'\n"
cat /etc/passwd | awk -F ':' '{print $1"|"$3"|"$7}'
