#!/bin/bash
echo "Q: Write a script which displays only the login, UID and Path of each entry of the /etc/passwd file.\n"
echo "A: We use the command line:
cat /etc/passwd | awk -F ':' '{print \$1\"|\"\$3\"|\"\$7}'\n"
cat /etc/passwd | awk -F ':' '{print $1"|"$3"|"$7}'
