# C enviroment

FROM debian

MAINTAINER Du Than <dthan@student.hive.fi>

RUN apt-get update && apt-get upgrade -y && apt-get install -y build-essential git

# C enviroment
# docker build -t bonus01 .
# docker run --rm -ti bonus01