#!/bin/bash
echo "Q: What file contains the RSA keys of systems that are authorized to connect via SSH?\n"
echo "A: ~/.ssh/authorized_keys
NOTE: The file contains public keys for public key authentication\n"
