#!/bin/bash
RED='\033[0;31m'
YELLOW='\033[1;33m'
echo "${RED}Q: Figure out the exact size of each folder of /var 
in a humanly understandable way followed by the path of it.\n"
echo "${YELLOW}A: du -sh /var/*"
du -sh /var/*
