#!/bin/bash
RED='\033[0;31m'
YELLOW='\033[1;33m'
echo "${RED}Q: Find the service which makes it possible to run specific tasks following a regular schedule\n"
echo "${YELLOW}A: cron
NOTE: man cron for more information"
