#!/bin/bash
echo"Q: Explain how connect yourself as new user. (With graphic session and ssh session)\n"
echo"A:
1. Graphic session: Prompting your login and password in the graphic session
2. SSH session: Run command 'ssh <user_name>@<ip_adress>\n"
