#!/bin/bash
echo"Explain how connect yourself as new user. (With graphic session and ssh session)\n"
echo"1. Graphic session: Prompting your login and password in the graphic session\n"
echo"2. SSH session: Run command 'ssh <user_name>@<ip_adress>\n"
